### ISSUE TITLE
Схема

### ISSUE THREAD

**Issue by mikeS7** [gavrilov-i/OpenTherm#2]
Можете полностью опубликовать схему? Из частичной из статьи на хабре, например, не очень понятно зачем резистор R10... и какой у него номинал?
Я использую opentherm gateway (http://otgw.tclcode.com), но подходит время сделать свой термостат

**Comment by gavrilov-i** [comment]
К сожалению не могу найти полной схемы - но в ней отлаживался только протокол - там нет остальной обвязки. R10, как и R3 - 1.5k - используется для защиты входов микросхемы в случае неправильного подключения. Назначение проводов в семе сверху вниз - питание +5В, TX (второй параметр конструктора OpenTherm - номер цифровгого пина Arduino), RX (первый параметр соответственно), земля.

**Comment by mikeS7** [comment]
Спасибо, опубликую схему, когда соберу и проверю
